const GRAMMAR_DB = [
  {
    id: 1,
    grammar: "〜ば〜のに／〜たら〜のに",
    meaning: "要是～的話就～了（帶有失望之感）",
    example_jp: "安かったら買うのに。",
    example_zh: "要是便宜的話就買了。",
    prefix: ["動詞ば形"],
    memorized: false,
  },
  {
    id: 2,
    grammar: "〜あげる",
    meaning: "我／我親友給予同輩他人～",
    example_jp: "私は友達にお土産をあげました。",
    example_zh: "我送了朋友伴手禮。",
    prefix: ["名詞"],
    memorized: false,
    page: 242,
    supplement: "A が B に〜あげる：A 給予 B",
  },
  {
    id: 3,
    grammar: "〜たらいいでしょか",
    meaning: "～的話才好呢？",
    example_jp: "どう行ったらいいでしょうか。",
    example_zh: "",
    prefix: ["動詞た形"],
    memorized: false,
  },
  {
    id: 4,
    grammar: "〜かねる",
    meaning: "（心理上的原因）很難～",
    example_jp: "妻としては、贅沢なゴルフ道具の購入に賛成しかねます。",
    example_zh: "作為妻子，對於購買奢侈的高爾夫器具我難以贊同。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 560,
  },
  {
    id: 5,
    grammar: "〜ばよかった／たらよかった",
    meaning: "要是～就好了（對當初沒有做的事情感到遺憾）",
    example_jp: "あっ、雨だ。傘を持って来ればよかった。",
    example_zh: "啊、下雨了。要是有帶傘來就好了。",
    prefix: ["動詞ば形"],
    memorized: false,
    page: 363,
    supplement:
      "如果是否定形「〜なければよかった」、「〜なかったらよかった」則表示對已經做了的事情感到後悔",
  },
  {
    id: 6,
    grammar: "〜（の）とおり",
    meaning: "正如〜",
    example_jp: "新しい先生は想像したとおり厳しいです。",
    example_zh: "新來的老師正如我想像的嚴格。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 317,
  },
  {
    id: 7,
    grammar: "〜ように言う",
    meaning: "命令、要求對方做到「ように」前面提到的內容",
    example_jp: "母に食事中にスマホをいじらないように言われました。",
    example_zh: "（被媽媽說吃飯時不要玩手機。）",
    prefix: ["動詞辭書形"],
    memorized: false,
  },
  {
    id: 8,
    grammar: "〜のか",
    meaning: "要求對方說明或詢問對方",
    example_jp: "どうして遅れたのか。",
    example_zh: "",
    prefix: ["動詞辭書形"],
    memorized: false,
  },
  {
    id: 9,
    grammar: "〜ようにしている",
    meaning: "已經在進行的長期習慣",
    example_jp: "毎日野菜を食べるようにしています。",
    example_zh: "（我每天都吃青菜。）→ 長期習慣",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 369,
  },
  {
    id: 10,
    grammar: "〜こそ",
    meaning: "正是～",
    example_jp: "あなたこそ嘘つきだ。",
    example_zh: "你才是說謊的人。",
    prefix: ["名詞"],
    memorized: false,
    page: 395,
  },
  {
    id: 11,
    grammar: "〜こと",
    meaning: "（使前面的修飾短句名詞化）",
    example_jp: "一番したいことはスキーです。",
    example_zh: "最想做的事是滑雪。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 153,
    supplement:
      "跟 のは／のが 不能互換的情況：後接 です、が大切だ、を約束する。",
  },
  {
    id: 12,
    grammar: "〜ということだ",
    meaning: "也就是說～（結論）",
    example_jp: "天気予報によると、台風が来るということだ。",
    example_zh: "根據天氣預報表示颱風即將到來。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 199,
    supplement: "根據前項情報，得到某種結論",
  },
  {
    id: 13,
    grammar: "〜というのは",
    meaning: "所謂的 A 就是 B",
    example_jp: "「ちょっと…」というのは、「都合が悪い」ということだ。",
    example_zh: "「那個……」就是「不方便」的意思。",
    prefix: ["動詞辭書形"],
    memorized: false,
  },
  {
    id: 14,
    grammar: "〜にしたがって",
    meaning: "隨著～",
    example_jp: "年をとるにしたがって、目が悪くなります。",
    example_zh: "隨著年齡增長，眼睛變得越來越差。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 318,
  },
  {
    id: 15,
    grammar: "〜ませんか",
    meaning: "勸誘、邀約",
    example_jp: "一緒に歌いませんか。",
    example_zh: "",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 129,
  },
  {
    id: 16,
    grammar: "〜ましょうか",
    meaning: "邀請一起做～／提議某個行動",
    example_jp: "窓をしめましょうか。",
    example_zh: "",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 129,
  },
  {
    id: 17,
    grammar: "〜ほうがいい〜",
    meaning: "建議不要怎麼做",
    example_jp: "夜から、何でも食べないほうがいいです。",
    example_zh: "",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 128,
    supplement: "巨匠 N4",
  },
  {
    id: 18,
    grammar: "〜でも",
    meaning: "就連～也",
    example_jp: "そのくらい、子供でもわかる。",
    example_zh: "",
    prefix: ["名詞"],
    memorized: false,
    page: 140,
  },
  {
    id: 19,
    grammar: "〜ことに",
    meaning: "值得（感情）的是～",
    example_jp: "残念なことに、クラスでトムさんだけが、試験に落ちてしまった。",
    example_zh: "令人感到不幸的是，湯姆是班上唯一沒有通過考試的人。",
    prefix: ["動詞た形", "形容詞"],
    memorized: false,
    page: 539,
  },
  {
    id: 20,
    grammar: "〜しか",
    meaning: "只能",
    example_jp: "この店では、カードしか使えません。",
    example_zh: "這家店只能刷卡。",
    prefix: ["名詞"],
    memorized: false,
    page: 22,
    supplement: "巨匠 N4",
  },
  {
    id: 21,
    grammar: "〜いっぽう（一方）",
    meaning: "越來越～",
    example_jp:
      "スマホを使う人の数は増える一方だ。　使用智慧型手機的人數不斷地增加。",
    example_zh: "",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 306,
    supplement: "多用於消極、不利語意",
  },
  {
    id: 22,
    grammar: "〜たび（に）",
    meaning: "每當～",
    example_jp: "この絵を見るたびに、涙が出てきて止まらない。",
    example_zh: "每當我看這幅畫時，眼淚總是忍不住掉了下來。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 427,
  },
  {
    id: 23,
    grammar: "〜とおもう",
    meaning: "想要～（說話當時有這樣的想法）",
    example_jp: "画家になろうと思います。",
    example_zh: "想要成為畫家。",
    prefix: ["動詞意向形"],
    memorized: false,
    page: 125,
  },
  {
    id: 24,
    grammar: "〜ことだ",
    meaning: "應當、就該～",
    example_jp: "日本語能力試験に合格したければ、毎日勉強することだ。",
    example_zh: "想要通過日語能力檢定，就該每天念書。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 546,
    supplement: "≒ ～したほうがいい",
  },
  {
    id: 25,
    grammar: "〜（な）のに",
    meaning: "明明～卻～",
    example_jp: "雨が降っているのに出かける。",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 227,
    supplement: "表達不滿情緒只能用 のに，不能用 けど。",
  },
  {
    id: 26,
    grammar: "〜ことになる",
    meaning: "（他人或自然）被決定要～",
    example_jp: "大学に合格したので、8月には引っ越すことになる。",
    example_zh: "因為考上了大學，所以八月要搬家。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 177,
  },
  {
    id: 27,
    grammar: "〜なんて／なんか",
    meaning: "1. 等等、之類 2. 竟然，表意外、懷疑 3. 輕視",
    example_jp: "そんなことをいうなんて、ひどい！",
    example_zh: "竟然講這種話，太過分了！",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 397,
  },
  {
    id: 28,
    grammar: "〜がほしい",
    meaning: "想要得到手～",
    example_jp: "今何がいちばんほしいですか。",
    example_zh: "現在你最想要的是什麼？",
    prefix: ["名詞"],
    memorized: false,
    page: 178,
  },
  {
    id: 29,
    grammar: "にしろにしろ／〜にせよ〜にせよ／〜にしても〜にしても",
    meaning: "～也好，～也好，都～",
    example_jp: "続けるにせよ辞めるにせよ、決めるのは早いほうがいい。",
    example_zh: "要繼續還是放棄，最好早點決定。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
  },
  {
    id: 30,
    grammar: "〜というより（も）",
    meaning: "與其說～不如說",
    example_jp: "あの人は外国人というよりハーフのようだ。",
    example_zh: "與其說那個人是外國人，不如說像是混血兒。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 527,
    supplement:
      "= というか　https://www.sigure.tw/learn-japanese/grammar/n3/62.php",
  },
  {
    id: 31,
    grammar: "〜てもかまわない",
    meaning: "即使～也沒關係～",
    example_jp: "何時帰ってもかまいませんよ。",
    example_zh: "",
    prefix: ["動詞て形", "形容詞"],
    memorized: false,
    page: 167,
  },
  {
    id: 32,
    grammar: "〜ものだ",
    meaning: "1. 竟然～\n  2. 就應該～",
    example_jp: "犬は吠えるものだよ。",
    example_zh: "狗本來就愛叫。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 544,
  },
  {
    id: 33,
    grammar: "〜とおもった",
    meaning:
      "（現在開始有這樣的想法，強調想法變化了）\n1. 意向形：想要～\n2. 辭書形、名詞、形容詞：覺得～",
    example_jp: "画家になろうと思いました。",
    example_zh: "開始想要成為畫家。",
    prefix: ["動詞意向形", "動詞辭書形", "名詞", "形容詞"],
    memorized: false,
  },
  {
    id: 34,
    grammar: "〜からには",
    meaning: "既然～",
    example_jp:
      "猫を飼おうと決めたからには、最後まで責任を持って飼ってください。",
    example_zh: "既然決定要養貓了，請負起責任養到最後。",
    prefix: ["動詞た形", "動詞辭書形"],
    memorized: false,
    page: 324,
  },
  {
    id: 35,
    grammar: "〜（自動詞）ている",
    meaning: "（與意圖無關的持續狀態）正在～／已經～了",
    example_jp: "雪が降っている。",
    example_zh: "正下著雪。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 87,
    supplement: "跟〜てある有語意差距",
  },
  {
    id: 36,
    grammar: "〜てもいい",
    meaning: "～也可以",
    example_jp: "日本語で話してもいいです。",
    example_zh: "說日文也可以。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 128,
  },
  {
    id: 37,
    grammar: "〜ことがある",
    meaning: "（有時）會發生～",
    example_jp: "ときどき、椅子で寝ることがあります。",
    example_zh: "（有時候會在椅子上睡著。）",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 206,
  },
  {
    id: 38,
    grammar: "〜ふりをする",
    meaning: "裝作～的樣子",
    example_jp: "平気なふりをしている。",
    example_zh: "裝作沒事的樣子。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    supplement:
      "「見て見ぬふりをする」是慣用句：視而不見https://www.sigure.tw/learn-japanese/grammar/n3/103.php",
  },
  {
    id: 39,
    grammar: "〜ましょう",
    meaning: "意志",
    example_jp: "一緒に歌いましょう。",
    example_zh: "",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 129,
  },
  {
    id: 40,
    grammar: "〜てばかりいる／〜ばかり〜ている",
    meaning: "老是、總是做～（負面）",
    example_jp: "彼はスマホばかり見ている。",
    example_zh: "他老是在看手機。",
    prefix: ["動詞て形", "名詞"],
    memorized: false,
    page: 303,
  },
  {
    id: 41,
    grammar: "〜のを",
    meaning: "（使前面的修飾短句名詞化）",
    example_jp: "佐藤さんが結婚するのを知っていますか",
    example_zh: "",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 153,
  },
  {
    id: 42,
    grammar: "〜といっても",
    meaning: "雖說～但是～",
    example_jp: "きれいだといっても、芸能人ほど美しくはない。",
    example_zh: "雖說很漂亮，但沒有藝人那樣美麗。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 493,
  },
  {
    id: 43,
    grammar: "〜にあたって / 〜にあたり",
    meaning: "在～的時候",
    example_jp: "ご結婚にあたって、心からお祝い申し上げます。",
    example_zh: "在你們結婚之際，我由衷地表示祝賀。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 456,
    supplement: "多用在重要場合如入學、結婚等",
  },
  {
    id: 44,
    grammar: "〜たい",
    meaning: "（第一人稱）想要～",
    example_jp: "まだ帰りたくないです。",
    example_zh: "還不想回家。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 122,
  },
  {
    id: 45,
    grammar: "〜だけで",
    meaning: "光是～就",
    example_jp: "犬の笑顔を考えただけで気分がよくなる。",
    example_zh: "狗的笑容光憑想像心情就會變好。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 395,
  },
  {
    id: 46,
    grammar: "〜かなあ",
    meaning: "不知會不會～；希望～",
    example_jp: "ちょっと手伝ってもらえるかな。",
    example_zh: "不知道你能不能幫我一下...？",
    prefix: ["動詞辭書形"],
    memorized: false,
    supplement: "＝かどうかわからない",
  },
  {
    id: 47,
    grammar: "〜として",
    meaning: "作為～（身份、資格、立場）",
    example_jp: "彼は男としては、背のほうが高いです。",
    example_zh: "他作為男生算個子高的。",
    prefix: ["名詞"],
    memorized: false,
    page: 324,
    supplement:
      "としては（就～而言）としても（作為～也）https://www.sigure.tw/learn-japanese/grammar/n3/68.php",
  },
  {
    id: 48,
    grammar: "〜て〜て",
    meaning: "連續做兩個或以上的動作或事情",
    example_jp: "友達と映画を見て、食事をした。",
    example_zh: "",
    prefix: ["動詞て形"],
    memorized: false,
    page: 105,
  },
  {
    id: 49,
    grammar: "〜たら",
    meaning: "如果～後，～",
    example_jp: "パソコンを買ったら、教えてね。",
    example_zh: "如果買了筆電，請告訴我。",
    prefix: ["動詞た形", "名詞", "形容詞"],
    memorized: false,
    page: 232,
    supplement: "常跟〜（の）なら〜比較",
  },
  {
    id: 50,
    grammar: "〜といった",
    meaning: "～等（列舉）",
    example_jp: "とんかつや天ぷらといった揚げ物の料理が好きです。",
    example_zh: "我喜歡炸豬排跟天婦羅等等這類炸物。",
    prefix: ["名詞"],
    memorized: false,
  },
  {
    id: 51,
    grammar: "〜さえ（も）",
    meaning: "甚至～（列舉某個極端例子來駁斥其他事物更不用提了）",
    example_jp: "北条さんは名前さえ書けない。",
    example_zh: "北条先生連自己的名字都不會寫。（更不用說寫其他東西了。）",
    prefix: ["動詞意向形", "動詞辭書形"],
    memorized: false,
    page: 525,
    supplement: "多數時候可與 でも 互換，但 でも 偏向列舉極端例子",
  },
  {
    id: 52,
    grammar: "〜とこは〜が",
    meaning: "雖然是～，但～",
    example_jp: "本は読んだことは読んだが、分からなかった。",
    example_zh: "書讀了是讀了，但讀不懂。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
  },
  {
    id: 53,
    grammar: "〜そう",
    meaning: "好像～",
    example_jp: "雨になりそうだよ。",
    example_zh: "看起來好像會下雨耶。",
    prefix: ["動詞ます形", "形容詞"],
    memorized: false,
    page: 188,
    supplement:
      "そう、よう、らしい 的差異：https://blog-tw.amazingtalker.com/blog/2017/3/17",
  },
  {
    id: 54,
    grammar: "〜たり〜たりする",
    meaning: "又是～，又是～",
    example_jp: "彼女は音楽を聴いたり、本を読んだりするのが好きです。",
    example_zh: "",
    prefix: ["動詞た形"],
    memorized: false,
    page: 88,
  },
  {
    id: 55,
    grammar: "〜まで",
    meaning: "1. 在～（時間）之前持續做\n2. 甚至～",
    example_jp: "年末まで、日本に行く。",
    example_zh: "年末之前，我會待在日本。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 138,
    supplement: "表示動作會持續到期限之前。",
  },
  {
    id: 56,
    grammar: "〜がする",
    meaning: "（感官上）感到～",
    example_jp: "最近、耳の中でかさかさと音がします。",
    example_zh: "最近耳朵裡面感覺有沙沙的聲音。",
    prefix: ["名詞"],
    memorized: false,
    page: 176,
    supplement:
      "感官上感受到傳來的感覺，如嗅覺、聽覺、味覺、觸覺、第六感等，多用於「氣味、聲音、口味、預感、發冷、想吐」https://www.sigure.tw/learn-japanese/grammar/n4/02.php",
  },
  {
    id: 57,
    grammar: "〜ながら",
    meaning: "一邊～一邊～",
    example_jp: "お茶を飲みながら、テレビを見ます。",
    example_zh: "",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 88,
    supplement: "巨匠 N4",
  },
  {
    id: 58,
    grammar: "〜なくてはいけない",
    meaning: "（社會常識上）必須～",
    example_jp: "勉強しなくてもいけません。",
    example_zh: "",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 164,
  },
  {
    id: 59,
    grammar: "〜に決まっている",
    meaning: "肯定是～",
    example_jp: "こんな趣味の悪いいたずらをするのはあいつに決まっている。",
    example_zh: "這種低級惡作劇肯定是那傢伙幹的。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
  },
  {
    id: 60,
    grammar: "〜につき",
    meaning: "[鄭重] 因為～",
    example_jp: "店内改装中につき、休業をしております。",
    example_zh: "因店內改裝中暫停營業。",
    prefix: ["名詞"],
    memorized: false,
    page: 279,
  },
  {
    id: 61,
    grammar: "〜たあとで〜",
    meaning: "做完～後，做～",
    example_jp: "仕事を終えた後で、友達と食事に行った。",
    example_zh: "",
    prefix: ["動詞た形"],
    memorized: false,
  },
  {
    id: 62,
    grammar: "〜（他動詞）てある",
    meaning: "（強調有意圖導致的持續狀態）已經～了",
    example_jp: "黒板に名前が書いてあります。",
    example_zh: "黑板上寫了名字",
    prefix: ["動詞て形"],
    memorized: false,
    page: 87,
    supplement: "跟〜ている有語意差距",
  },
  {
    id: 63,
    grammar: "〜ようにする",
    meaning: "為了達到前項內容而努力，是一種下決心要培養的習慣",
    example_jp: "今日から野菜も食べるようにする。",
    example_zh: "（從今天開始也吃青菜。）",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 369,
  },
  {
    id: 64,
    grammar: "〜たばかりだ",
    meaning: "剛剛做完～",
    example_jp: "友達と会ったばかりです。",
    example_zh: "",
    prefix: ["動詞た形"],
    memorized: false,
    supplement: "=たて",
  },
  {
    id: 65,
    grammar: "〜（の）はず",
    meaning: "1. （照理說）應該～\n2. 難怪～",
    example_jp: "宿泊契約では一泊二食のはずだった。",
    example_zh: "根據住宿契約應該是一宿兩餐。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 188,
    supplement: "個人根據事實或知識的主觀推論。",
  },
  {
    id: 66,
    grammar: "〜（自動詞）ように",
    meaning: "為了／為了不（讓現象發生）～",
    example_jp: "いい点数が取れるように、毎日勉強している。",
    example_zh: "為了得到好成績，每天用功唸書。",
    prefix: ["動詞可能形", "動詞辭書形"],
    memorized: false,
  },
  {
    id: 67,
    grammar: "〜ことにする",
    meaning: "（自己）決定要～",
    example_jp: "眠くなったので、今日はもう寝ることにする。",
    example_zh: "變得有點睏，我決定要睡覺了。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 177,
  },
  {
    id: 68,
    grammar: "〜っぱなし",
    meaning: "做了某動作之後就不管了",
    example_jp: "電気をつけっぱなしで寝てしまった。",
    example_zh: "開著燈就睡著了。",
    prefix: ["動詞ます形"],
    memorized: false,
    supplement:
      "「っぱなし」的用法相當於「～まま」，差別在於「っぱなし」多帶有負面評價。https://www.sigure.tw/learn-japanese/grammar/n3/44.php",
  },
  {
    id: 69,
    grammar: "〜というものだ",
    meaning: "這就是所謂的～（感想）",
    example_jp: "何でも話し合える、それが友達というものだ。",
    example_zh: "什麼話都可以聊的人，就是所謂的朋友。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 568,
  },
  {
    id: 70,
    grammar: "〜ほど〜ない",
    meaning: "沒有（前項）那麼（後項）～",
    example_jp: "風は思っていたほど冷たくなかった。",
    example_zh: "風沒有想像中的冷。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 313,
  },
  {
    id: 71,
    grammar: "〜（の）まま",
    meaning: "表狀態持續",
    example_jp: "そのまま動かないでください。",
    example_zh: "請保持那樣不要動。",
    prefix: ["動詞た形", "名詞", "形容詞"],
    memorized: false,
    page: 317,
  },
  {
    id: 72,
    grammar: "〜なさい",
    meaning: "請～（命令）",
    example_jp: "勉強しなさい。",
    example_zh: "",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 163,
  },
  {
    id: 73,
    grammar: "〜ておく／〜とく",
    meaning: "事先做～",
    example_jp: "旅行の前に、切符を買っておく。",
    example_zh: "旅行の前に、切符を買っておきます。",
    prefix: ["動詞て形"],
    memorized: false,
    supplement: "巨匠 N4",
  },
  {
    id: 74,
    grammar: "〜を〜とする",
    meaning: "把 A 當作 B",
    example_jp: "服を雑巾とします。",
    example_zh: "把衣服直接拿來抹布使用",
    prefix: ["名詞"],
    memorized: false,
    page: 550,
  },
  {
    id: 75,
    grammar: "〜たことがある／ない",
    meaning: "（過去）發生過～",
    example_jp: "私は日本に行ったことがあります。",
    example_zh: "",
    prefix: ["動詞た形"],
    memorized: false,
    page: 206,
  },
  {
    id: 76,
    grammar: "〜ばかりか〜（も／さえ／まで）",
    meaning: "不僅～而且",
    example_jp: "説明が少ないばかりか、意味も分からない。",
    example_zh: "不僅是說明少，也不懂意思。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 378,
    supplement: "表示除前項情況以外，後項程度更甚。",
  },
  {
    id: 77,
    grammar: "〜しだい（次第）",
    meaning: "1. 演變成～結果\n  2. 一～就馬上",
    example_jp: "試験の結果がわかり次第、電話でお伝えします。",
    example_zh: "",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 463,
    supplement: "日檢常考",
  },
  {
    id: 78,
    grammar: "〜かどうか",
    meaning: "是否～",
    example_jp: "彼が来るかどうかわかりません。",
    example_zh: "我不知道他會不會來。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 142,
  },
  {
    id: 79,
    grammar: "〜なくてはならない",
    meaning: "（社會常識上）必須～",
    example_jp: "毎日、運動して体を鍛えなくてもなりません。",
    example_zh: "",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 165,
  },
  {
    id: 80,
    grammar: "〜（な）ので",
    meaning: "（客觀的）因為～所以～",
    example_jp: "私は風邪をひいたので、学校を休みます。",
    example_zh: "由於我感冒了，所以要向學校請假。",
    prefix: ["動詞た形", "名詞", "形容詞"],
    memorized: false,
    supplement:
      "「から」→「主觀描述、較不客氣、強硬」\n「ので」→「客觀描述、比較委婉、尊重」",
  },
  {
    id: 81,
    grammar: "〜のが",
    meaning: "（使前面的修飾短句名詞化）表示喜好、能力",
    example_jp: "日本語能力試験に合格したければ、毎日勉強することだ。",
    example_zh: "想要通過日語能力檢定，就該每天念書。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 153,
  },
  {
    id: 82,
    grammar: "〜てから",
    meaning: "1. 先做～再做～\n2. 從某個時間點之後～",
    example_jp: "彼は、テレビに出てから有名になった。",
    example_zh: "他自從上電視後，就開始有名氣了。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 104,
  },
  {
    id: 83,
    grammar: "〜ずに（＝ないで）",
    meaning: "沒有做～就～",
    example_jp: "電気を消さずに寝てしまった。",
    example_zh: "沒有關燈就睡了。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 99,
  },
  {
    id: 84,
    grammar: "〜によると／によれば",
    meaning: "根據（傳言）〜",
    example_jp: "天気予報によると、来週台風が来るそうだ。",
    example_zh: "根據氣象預報，下周有颱風會來。",
    prefix: ["名詞"],
    memorized: false,
    page: 448,
    supplement:
      "による 常跟 によると 搞混\n文末常以「そうだ」、「ということだ」、「とのことだ」、「んだって」相呼應。",
  },
  {
    id: 85,
    grammar: "〜を〜にする",
    meaning: "將Ａ修改成Ｂ使用",
    example_jp: "服を雑巾にします。",
    example_zh: "把衣服剪裁成抹布大小後，拿來當抹布使用",
    prefix: ["名詞"],
    memorized: false,
  },
  {
    id: 86,
    grammar: "〜たがる",
    meaning: "（第三人稱）顯露在外的希望",
    example_jp: "彼女は、理由を言いたがらない。",
    example_zh: "她不想說理由。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 180,
  },
  {
    id: 87,
    grammar: "〜はもちろん／はもとより",
    meaning: "～不用說，（後項也不意外）",
    example_jp: "彼は卓球はもちろん、テニスもうまい。",
    example_zh: "他的桌球不用說，網球也很厲害。",
    prefix: ["名詞"],
    memorized: false,
    page: 378,
  },
  {
    id: 88,
    grammar: "〜（の）なら",
    meaning: "如果～，先～",
    example_jp: "パソコンを買うなら、教えてね。",
    example_zh: "如果要買電腦，請先告訴我。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 234,
    supplement:
      "1. 通常以對方所說的事情會發生為前提，說話人提出勸告、意志、請求等。\n2. 常跟〜たら〜比較",
  },
  {
    id: 89,
    grammar: "〜について",
    meaning: "關於～",
    example_jp: "私は映画についても興味があります。",
    example_zh: "關於電影我也很有興趣。",
    prefix: ["名詞"],
    memorized: false,
    page: 201,
  },
  {
    id: 90,
    grammar: "〜ほど",
    meaning: "1. 大約\n  2. 甚至到～程度",
    example_jp: "これほど多くの人が日本語を勉強しているのか。",
    example_zh: "這麼多人在學日語嗎。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 312,
    supplement:
      "ほど經常可以和くらい互換https://www.sigure.tw/learn-japanese/grammar/n3/108.php",
  },
  {
    id: 91,
    grammar: "〜らしい",
    meaning: "（眼前客觀觀察）好像～",
    example_jp: "明日は雨が降るらしいです。／今年の冬は寒いらしい。",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 191,
  },
  {
    id: 92,
    grammar: "〜といい（のに）",
    meaning: "（勸誘對方行為）～就好了\n希望某個願望成真",
    example_jp: "お母さんはもっとやさしいといいんだけど。",
    example_zh: "媽媽要是能再溫柔一點就好了。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 158,
    supplement:
      "可與〜たら（いいのに）／〜ば（いいのに）互換，表假定條件的「と」用於尚未發生的事情https://www.sigure.tw/learn-japanese/grammar/n3/59.php",
  },
  {
    id: 93,
    grammar: "〜とおもっている",
    meaning:
      "（從以前就有這樣的想法）\n1. 意向形：想要～\n2. 辭書形、名詞、形容詞：覺得～",
    example_jp: "画家になろうと思っています。",
    example_zh: "一直想要成為畫家。",
    prefix: ["動詞意向形", "動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 186,
  },
  {
    id: 94,
    grammar: "〜ところだった",
    meaning: "差一點就要～了",
    example_jp: "もう少しでバスの発車時刻に間に合わないところだった。",
    example_zh: "差點就趕不上公車的發車時間。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 432,
  },
  {
    id: 95,
    grammar: "〜わりに（は）",
    meaning: "雖然～但相對還算～",
    example_jp: "この国は、熱帯のわりには過ごしやすい。",
    example_zh: "這個國家雖然在熱帶，但住起來相對算舒適的。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 313,
    supplement: "表示結果跟前項條件不成比例",
  },
  {
    id: 96,
    grammar: "〜のまえに",
    meaning: "在～之前～（空間上）",
    example_jp: "駅の前に銀行があります。",
    example_zh: "車站前面有銀行。",
    prefix: ["名詞"],
    memorized: false,
    page: 106,
    supplement: "若是指時間的之前，則不會加 の",
  },
  {
    id: 97,
    grammar: "〜あがる／あげる",
    meaning: "徹底完成",
    example_jp: "ピザが焼きあがりました。",
    example_zh: "披薩烤好了。（自動詞）",
    prefix: ["動詞ます形"],
    memorized: false,
  },
  {
    id: 98,
    grammar: "〜いじょう（は）",
    meaning: "既然～就要～",
    example_jp: "日本に来た以上は、京都に一度行ってみたい。",
    example_zh: "既然來到日本，就想去去看京都一次。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 468,
  },
  {
    id: 99,
    grammar: "〜とおもっていた",
    meaning:
      "（以前有這樣的意志，但現在沒有）\n1. 意向形：想要～\n2. 辭書形、名詞、形容詞：覺得～",
    example_jp: "画家になろうと思っていました。",
    example_zh: "曾經想要成為畫家。",
    prefix: ["動詞意向形", "動詞辭書形", "名詞", "形容詞"],
    memorized: false,
  },
  {
    id: 100,
    grammar: "〜ついで（に）",
    meaning: "順便～",
    example_jp: "スーパーへ行くついでに、車にガソリンを入れました。",
    example_zh: "去超市順便加油。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 373,
  },
  {
    id: 101,
    grammar: "〜てはだめです",
    meaning: "不可以做",
    example_jp: "しばらくお酒を飲んではだめです。",
    example_zh: "暫時不行喝酒。",
    prefix: ["動詞て形"],
    memorized: false,
    supplement:
      "相較 V てはいけません 偏向一般論 ，てはだめです 是針對聽者的行為",
  },
  {
    id: 102,
    grammar: "〜すぎる",
    meaning: "過於～",
    example_jp: "昨日、食べすぎたんです。",
    example_zh: "君は自分に自信がなさすぎるよ。",
    prefix: ["動詞ます形", "形容詞"],
    memorized: false,
    page: 198,
  },
  {
    id: 103,
    grammar: "〜っぽい",
    meaning: "強烈的～傾向（較常用於負面傾向）",
    example_jp: "この格好は男っぽいね。",
    example_zh: "這個穿著很有男人味",
    prefix: ["動詞ます形", "名詞"],
    memorized: false,
    page: 306,
    supplement: "らしい 是正面評價",
  },
  {
    id: 104,
    grammar: "〜ほかない／しかない",
    meaning: "別無他法只能～",
    example_jp: "終電に乗り遅れたし、歩いて帰るしかない。",
    example_zh: "沒趕上最後一班電車，只能走路回去。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 353,
  },
  {
    id: 105,
    grammar: "〜いくら（どんなに）ても／でも",
    meaning: "即使再怎麼～也～",
    example_jp: "いくら話しても、分かってくれない。",
    example_zh: "說了說少次，他也不會懂。",
    prefix: ["動詞て形", "名詞", "形容詞"],
    memorized: false,
  },
  {
    id: 106,
    grammar: "〜ないと",
    meaning: "不～就（有負面結果）",
    example_jp: "早く帰らないと母に叱られる。",
    example_zh: "不趕快回家的話會被媽媽罵。",
    prefix: ["動詞否定形", "名詞", "形容詞"],
    memorized: false,
  },
  {
    id: 107,
    grammar: "〜てみる",
    meaning: "嘗試做～",
    example_jp: "日本語の歌を歌ってみましたが、難しいですね。",
    example_zh: "",
    prefix: ["動詞て形"],
    memorized: false,
    page: 172,
  },
  {
    id: 108,
    grammar: "〜というと／〜といえば",
    meaning: "說到～的話",
    example_jp: "東京というと、東京タワーを思い出す。",
    example_zh: "說到東京的話，就會想到東京鐵塔。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 480,
  },
  {
    id: 109,
    grammar: "〜てしまう／ちゃう",
    meaning: "1. 表示動作徹底完成\n  2. 表遺憾、糟糕情緒",
    example_jp: "亀が死んでしまいました。",
    example_zh: "遺憾烏龜死掉了。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 110,
  },
  {
    id: 110,
    grammar: "〜ないで（ください）",
    meaning: "請不要～",
    example_jp: "ドアを閉めないで（ください）。",
    example_zh: "",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 124,
  },
  {
    id: 111,
    grammar: "〜にくらべて",
    meaning: "跟～比較起來",
    example_jp: "今年は去年に比べて雪が少ない。",
    example_zh: "今年的雪比去年少。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 375,
  },
  {
    id: 112,
    grammar: "〜てごらん",
    meaning: "試試看～",
    example_jp: "何が欲しいの？言ってごらん。",
    example_zh: "你想要什麼？說說看。",
    prefix: ["動詞て形"],
    memorized: false,
  },
  {
    id: 113,
    grammar: "〜ないではいられない／ずにはいられない",
    meaning: "忍不住～",
    example_jp: "花を見ると買わないではいられない。",
    example_zh: "一看到花就忍不住買。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 553,
    supplement:
      "表達因無法抑制某種情感而採取的行動https://aiueo.cc/pages/cht/grammar/web/477.php",
  },
  {
    id: 114,
    grammar: "〜ず（＝なくで）",
    meaning: "因為沒有，所以～",
    example_jp: "家族に会えず、寂しいです。",
    example_zh: "見不到家人，覺得很寂寞。",
    prefix: ["動詞否定形", "名詞", "形容詞"],
    memorized: false,
    supplement: "ず：前文可獨立。\nずに：前文無法獨立，若獨立通常是省略用法。",
  },
  {
    id: 115,
    grammar: "〜ばかりだ",
    meaning: "越來越～（負面）",
    example_jp: "薬を飲んでいるのに、症状は悪くなるばかりだ。",
    example_zh: "雖然吃了藥，但症狀越來越糟了。",
    prefix: ["動詞辭書形"],
    memorized: false,
  },
  {
    id: 116,
    grammar: "〜きり",
    meaning: "只有、僅",
    example_jp: "今度、二人きりで映画を見に行きましょう。",
    example_zh: "下次就我們兩個人一起去看電影吧。",
    prefix: ["動詞た形", "名詞"],
    memorized: false,
    page: 508,
    supplement:
      "あれきり、それきり為既定單詞https://www.sigure.tw/learn-japanese/grammar/n3/16.php",
  },
  {
    id: 117,
    grammar: "〜ようになる",
    meaning: "無能力到有能力的轉變",
    example_jp: "爺ちゃんもやっとパソコンが使えるようになった。",
    example_zh: "爺爺終於也會用電腦了。（原本不會用電腦，變得會用電腦了。）",
    prefix: ["動詞意向形"],
    memorized: false,
    page: 368,
  },
  {
    id: 118,
    grammar: "〜とする",
    meaning: "正打算做、還未達成",
    example_jp: "出かけようとしたとき、友達が来ました。",
    example_zh: "正要出門時朋友就來了。",
    prefix: ["動詞意向形"],
    memorized: false,
    supplement:
      "～（よ）うとしない：不願https://www.sigure.tw/learn-japanese/grammar/n4/31.php",
  },
  {
    id: 119,
    grammar: "〜において",
    meaning: "在～地點、方面、時間等",
    example_jp: "コンサートはアリーナにおいて行われる。",
    example_zh: "演唱會在小巨蛋舉行。",
    prefix: ["名詞"],
    memorized: false,
    page: 325,
    supplement: "較鄭重，一般可與「で」互換",
  },
  {
    id: 120,
    grammar: "〜ことはない／こともない",
    meaning: "用不著〜",
    example_jp: "心配することはないよ。明日は明日の風が吹くんだから。",
    example_zh: "用不著擔心，總會有辦法的。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 287,
  },
  {
    id: 121,
    grammar: "〜ばかりに",
    meaning: "就因為～",
    example_jp: "その言葉を信じたばかりにひどい目にあった。",
    example_zh: "因為相信那句話而倒了大霉。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 476,
  },
  {
    id: 122,
    grammar: "〜ことか",
    meaning: "多麼～啊（加強感嘆語氣）",
    example_jp:
      "世界を救える発明はどれほど偉いことか！能夠拯救世界的發明是多麼地偉大啊！",
    example_zh: "",
    prefix: ["形容詞"],
    memorized: false,
    page: 574,
  },
  {
    id: 123,
    grammar: "〜（他動詞）ために",
    meaning: "為了做到～",
    example_jp: "家を買うために、貯金しています。",
    example_zh: "為了買房子而存錢。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 342,
  },
  {
    id: 124,
    grammar: "〜のは",
    meaning: "（使前面的修飾短句名詞化）表示意見、感想，或強調某事",
    example_jp: "いろいろな国の人と話すのは楽しいです。",
    example_zh: "",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 153,
  },
  {
    id: 125,
    grammar: "〜てください",
    meaning: "請～",
    example_jp: "ちょっと待ってください。",
    example_zh: "",
    prefix: ["動詞て形"],
    memorized: false,
    page: 124,
  },
  {
    id: 126,
    grammar: "〜ものか",
    meaning: "怎麼會、哪可能",
    example_jp: "あんな噂好きな人に悩みなんか言うものか。",
    example_zh: "我怎麼可能跟那種喜歡八卦的人說煩惱。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 346,
    supplement:
      "比較禮貌的說法是「ものですか」https://www.sigure.tw/learn-japanese/grammar/n3/117.php",
  },
  {
    id: 127,
    grammar: "〜がる",
    meaning: "感到",
    example_jp: "彼は新しい携帯を自慢して、嬉しがっている。",
    example_zh:
      "他炫耀他的新手機，得意忘形的樣子。（炫耀手機是會讓人不悅的事情，這句話表達說話者輕蔑的心情。）",
    prefix: ["形容詞"],
    memorized: false,
    page: 178,
  },
  {
    id: 128,
    grammar: "〜てはじめて",
    meaning: "在～之後才～",
    example_jp: "子育ての大変さって、やってみてはじめてわかる。",
    example_zh: "養育孩子的辛苦，自己試了才知道。",
    prefix: ["動詞て形"],
    memorized: false,
  },
  {
    id: 129,
    grammar: "〜つもり",
    meaning: "（事前決定好）打算～",
    example_jp: "夏休みには旅行に行くつもりです。",
    example_zh: "我打算暑假去旅行。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 125,
    supplement:
      "相對 と思います 更對某件事抱有具體的計畫 https://www.sigure.tw/learn-japanese/grammar/n4/38.php",
  },
  {
    id: 130,
    grammar: "〜てはいけません",
    meaning: "禁止",
    example_jp: "この川で泳いではいけません。",
    example_zh: "禁止在此河川游泳。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 160,
  },
  {
    id: 131,
    grammar: "〜けれど（も）、けど",
    meaning: "雖然、可是",
    example_jp: "このかばんは丈夫だけど、重くて大変です＞",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 98,
    supplement: "けど 比 けれど 隨便",
  },
  {
    id: 132,
    grammar: "〜とき",
    meaning: "～的時候",
    example_jp: "満点を取ったときは、嬉しいです。",
    example_zh: "考滿分的時候，很高興。",
    prefix: ["動詞た形", "動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 103,
    supplement:
      "- 動詞辭書形、形容詞、名詞 + とき：在前項的狀態下，同時有後項動作\n- 動詞過去式 + とき、動詞現在式：先有前者，後者才成立\n- 動詞現在式 + とき、動詞過去式：後者先發生，前者才發生",
  },
  {
    id: 133,
    grammar: "〜あとで",
    meaning: "～以後",
    example_jp: "授業が終わった後で、友達とお台場に行きます。",
    example_zh: "下課後，跟朋友去台場",
    prefix: ["動詞た形"],
    memorized: false,
    page: 105,
  },
  {
    id: 134,
    grammar: "〜まえに",
    meaning: "在～之前～（時間上）",
    example_jp: "昨日、ご飯を食べる前に、手を洗いました。",
    example_zh: "昨天吃飯前洗手了。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 106,
    supplement: "即使句尾是過去式，也要用辭書形",
  },
  {
    id: 135,
    grammar: "〜ほしい",
    meaning: "希望你做～",
    example_jp: "ピサを注文してほしいです。",
    example_zh: "我希望你叫披薩。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 178,
  },
  {
    id: 136,
    grammar: "〜でしょう",
    meaning: "推測可能～吧",
    example_jp: "明日もいい天気でしょう。",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 130,
    supplement: "降調，表示推測，不像 です 那麼肯定",
  },
  {
    id: 137,
    grammar: "〜より〜（の）ほう〜",
    meaning: "比起⋯更⋯",
    example_jp: "紅茶よりコーヒーのほうが好きです。",
    example_zh: "比起紅茶，更喜歡咖啡。",
    prefix: ["名詞"],
    memorized: false,
    page: 131,
    supplement:
      "對兩件事物比較後，選擇了 ほう 前面的事物。より跟 ほう的順序可以調換。",
  },
  {
    id: 138,
    grammar: "〜あまり〜ない",
    meaning: "不怎麼～",
    example_jp: "このカレー、あまり美味しくないです。",
    example_zh: "這個咖哩不怎麼好吃。",
    prefix: ["名詞"],
    memorized: false,
    page: 132,
  },
  {
    id: 139,
    grammar: "〜までに",
    meaning: "在～（時間）之前做",
    example_jp: "年末までに、日本に行く。",
    example_zh: "年末之前，我會去日本。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 138,
    supplement: "表示動作在期限之前的某時間點執行",
  },
  {
    id: 140,
    grammar: "〜ても／でも",
    meaning: "即使～也",
    example_jp: "字が下手でも、丁寧に書くことが大切です。",
    example_zh: "即使寫字很醜，重要的事一筆一劃仔細寫。",
    prefix: ["動詞て形", "形容詞"],
    memorized: false,
    page: 141,
    supplement:
      "1. 動詞 て 形 + ても\n2. 形容詞 く + ても\n3. 名詞、形容動詞 + でも",
  },
  {
    id: 141,
    grammar: "〜なければならない",
    meaning: "（社會常識上）必須～",
    example_jp: "学生は勉強しなければならない。",
    example_zh: "學生必須用功唸書。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 163,
  },
  {
    id: 142,
    grammar: "〜ないわけにはいかない",
    meaning: "（不情願）不得不",
    example_jp: "行かないわけにはいかない。",
    example_zh: "不得不去。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 165,
  },
  {
    id: 143,
    grammar: "〜べきだ",
    meaning: "（做人原則上）必須～",
    example_jp: "弱い者をいじめるのは、やめるべきだ。",
    example_zh: "",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 164,
  },
  {
    id: 144,
    grammar: "〜ないこともない",
    meaning: "也不是沒有～",
    example_jp: "一人暮らしが寂しいと思わないこともない。",
    example_zh: "一個人生活也不是沒感到寂寞過。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 287,
  },
  {
    id: 145,
    grammar: "〜てみせる",
    meaning: "做給別人看",
    example_jp: "今度は合格してみせる。",
    example_zh: "我這次絕對會考過給你看。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 172,
  },
  {
    id: 146,
    grammar: "〜にする",
    meaning: "決定（某事物）",
    example_jp: "私はラーメンにします。",
    example_zh: "我要吃拉麵。",
    prefix: ["名詞"],
    memorized: false,
    page: 176,
  },
  {
    id: 147,
    grammar: "〜かもしれない",
    meaning: "也許～",
    example_jp: "暗くなってきた。雨になるかもしれない。",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 186,
    supplement: "個人推測把握度：〜とおもう > だろう > かもしれない",
  },
  {
    id: 148,
    grammar: "〜（の）はずがない",
    meaning: "（照理說）不可能～",
    example_jp: "七月の雪が降るがはずがない。",
    example_zh: "七月不可能下雪。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 188,
    supplement: "個人根據事實或知識的主觀推論。",
  },
  {
    id: 149,
    grammar: "〜そうだ",
    meaning: "聽說（從別人、報章雜誌聽說）",
    example_jp: "先輩の話では、彼はテニスが上手だそうだ。",
    example_zh: "從學長姐那裡聽說，他的網球打得很好。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 199,
    supplement: "不能改否定或過去式。",
  },
  {
    id: 150,
    grammar: "〜（の）ような",
    meaning: "像～一樣",
    example_jp: "あそこに羊のような形の雲があります。",
    example_zh: "那邊有一朵形狀像綿羊的雲。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 190,
  },
  {
    id: 151,
    grammar: "〜みたい",
    meaning: "像～一樣（口語）",
    example_jp: "髪に虫みたいなのがついているよ。",
    example_zh: "你頭髮上黏著好像是蟲的東西。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 190,
    supplement: "不是很確定的推測",
  },
  {
    id: 152,
    grammar: "〜ことができる",
    meaning: "能～",
    example_jp: "私も会場の入ることができますか。",
    example_zh: "我也可以進會場嗎？",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 196,
  },
  {
    id: 153,
    grammar: "〜やすい",
    meaning: "容易～",
    example_jp: "このスカートは、茶色なのでコーデイネートしやすいです。",
    example_zh: "那間裙子是褐色的，所以很好搭配。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 197,
    supplement: "～にくい：很難～",
  },
  {
    id: 154,
    grammar: "〜すぎだ",
    meaning: "過於～",
    example_jp: "あの子はちょっと痩せすぎだ。",
    example_zh: "那個小孩有點太瘦了。",
    prefix: ["動詞て形", "形容詞"],
    memorized: false,
    page: 199,
    supplement: "～すぎる：結合單字做動詞使用\n〜すぎだ：結合單字做名詞使用",
  },
  {
    id: 155,
    grammar: "〜という",
    meaning: "叫做～",
    example_jp: "息子から金を送ってくれという電話が来た。",
    example_zh: "兒子打了電話來要錢。",
    prefix: ["名詞"],
    memorized: false,
    page: 200,
  },
  {
    id: 156,
    grammar: "〜という／書く／聞く",
    meaning: "說是、寫說、聽說（引用）",
    example_jp: "上司の「明日から来なくていい」と言わました。",
    example_zh: "我被上司說「明天起不必再來了」。",
    prefix: ["名詞"],
    memorized: false,
    page: 200,
  },
  {
    id: 157,
    grammar: "〜にたいして",
    meaning: "針對～",
    example_jp: "彼の考えにたいして、私は反対意見を述べた。",
    example_zh: "對於他的想法，我陳述了反對意見。",
    prefix: ["名詞"],
    memorized: false,
    page: 327,
  },
  {
    id: 158,
    grammar: "〜と",
    meaning: "一～就～",
    example_jp: "氷が溶けると水になる。",
    example_zh: "冰溶化就變成水。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 232,
  },
  {
    id: 159,
    grammar: "〜ば",
    meaning: "如果～的話～",
    example_jp: "時間が合えば、会いたいです。",
    example_zh: "時間允許的話，想見一面。",
    prefix: ["動詞ば形"],
    memorized: false,
    page: 233,
  },
  {
    id: 160,
    grammar: "〜たら〜た",
    meaning: "（因為前項動作成立才發生）發現～",
    example_jp: "トイレに入ったら、紙がなかった。",
    example_zh: "進廁所後，才發現沒有衛生紙了。",
    prefix: ["動詞た形"],
    memorized: false,
    page: 235,
    supplement: "因果關係更強，後面一定接た形",
  },
  {
    id: 161,
    grammar: "〜たところ",
    meaning: "1. 結果（或不翻譯）",
    example_jp: "あなたのうちを訪ねたところ、引っ越した後だった。",
    example_zh: "拜訪他家的時候，才發現他已經搬走了。",
    prefix: ["動詞た形"],
    memorized: false,
    page: 236,
    supplement: "帶有說話人訝異的語感，前後像沒有絕對因果關係。",
  },
  {
    id: 162,
    grammar: "〜てあげる",
    meaning: "我／我親友為同輩他人做～",
    example_jp: "私は友達に宿題を手伝ってあげました。",
    example_zh: "我幫朋友寫了作業。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 243,
  },
  {
    id: 163,
    grammar: "〜やる",
    meaning: "我／我親友給予後輩他人～",
    example_jp: "私は息子にスマホーをやりました。",
    example_zh: "我給了兒子手機。",
    prefix: ["名詞"],
    memorized: false,
    page: 242,
  },
  {
    id: 164,
    grammar: "〜てやる",
    meaning: "我／我親友為後輩他人做～",
    example_jp: "私は息子の宿題を手伝ってやりました。",
    example_zh: "我幫兒子一起寫了作業。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 243,
    supplement:
      "1. 說話者以給予利益的心情為他人做有益的事\n2. 說話人帶有不滿或積極意志，而做讓對方困擾的事。（我覺得就是在貶低對方）",
  },
  {
    id: 165,
    grammar: "〜さしあげる",
    meaning: "[謙讓] 我／我親友給予前輩他人～",
    example_jp: "今週中にご連絡を差し上げます。",
    example_zh: "本週內會跟您聯繫。",
    prefix: ["名詞"],
    memorized: false,
    page: 244,
  },
  {
    id: 166,
    grammar: "〜てさしあげる",
    meaning: "[謙讓] 我／我親友為前輩他人做～",
    example_jp: "私は先生に資料を整理して差し上げました。",
    example_zh: "我協助整理了老師的資料。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 245,
  },
  {
    id: 167,
    grammar: "〜いただく",
    meaning: "[謙讓] 我／我親友承蒙前輩他人給我～",
    example_jp: "先生に絵をいただきました。",
    example_zh: "我從老師那邊收到了畫作。",
    prefix: ["名詞"],
    memorized: false,
    page: 244,
  },
  {
    id: 168,
    grammar: "〜ていただく",
    meaning: "[謙讓] 我／我親友承蒙前輩他人為我做～",
    example_jp: "先生に良い参考書を教えていただきました。",
    example_zh: "承蒙老師告訴我有用的參考書。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 245,
  },
  {
    id: 169,
    grammar: "〜もらう",
    meaning: "A 從同輩他人那裡得到～",
    example_jp: "彼は友達に団子をもらいました。",
    example_zh: "他從朋友那裡得到丸子。",
    prefix: ["名詞"],
    memorized: false,
    page: 246,
  },
  {
    id: 170,
    grammar: "〜てもらう",
    meaning: "我／我親友請同輩他人為我做～",
    example_jp: "友達に宿題をやってもらった。",
    example_zh: "請朋友幫忙寫了作業。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 247,
  },
  {
    id: 171,
    grammar: "〜くれる",
    meaning: "同輩他人給我／我親友～",
    example_jp: "友達は私に団子をくれました。",
    example_zh: "朋友給了我丸子。",
    prefix: ["名詞"],
    memorized: false,
    page: 247,
  },
  {
    id: 172,
    grammar: "〜てくれる",
    meaning: "同輩他人為我／我親友做～",
    example_jp: "友達は私に宿題をやってくれました。",
    example_zh: "朋友幫我寫了作業。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 247,
  },
  {
    id: 173,
    grammar: "〜くださる",
    meaning: "[尊敬] 前輩他人給我／我親友～",
    example_jp: "先生は果物をくださいました。",
    example_zh: "老師送了水果給我。",
    prefix: ["名詞"],
    memorized: false,
    page: 249,
  },
  {
    id: 174,
    grammar: "〜てくださる",
    meaning: "[尊敬] 前輩他人為我／我親友做～",
    example_jp: "部長、その資料を貸してくださいませんか。",
    example_zh: "部長，您方便借我那份資料嗎？",
    prefix: ["動詞て形"],
    memorized: false,
    page: 250,
  },
  {
    id: 175,
    grammar: "〜（ら）れる",
    meaning: "被～",
    example_jp: "好きな人に見られた。",
    example_zh: "被喜歡的人看見了。",
    prefix: ["動詞受身形"],
    memorized: false,
    page: 256,
    supplement:
      "1. 直接承受別人的動作\n2. 社會活動的客觀描述\n3. 因某人行為或天氣，間接受到麻煩",
  },
  {
    id: 176,
    grammar: "〜（さ）せる",
    meaning: "要求～",
    example_jp: "子供に家事の手伝いをさせた。",
    example_zh: "要求小孩幫忙了家事。",
    prefix: ["動詞使役形"],
    memorized: false,
    page: 257,
    supplement:
      "1. 某人強迫他人做某事\n2. 用言行促使他人自然地做某種行為，通常用人難以控制的情緒動詞",
  },
  {
    id: 177,
    grammar: "〜（さ）せておく",
    meaning: "放任～",
    example_jp: "彼女を悲しませておいて、何を言うんだ。",
    example_zh: "你讓她那麼難過，還說這種話。",
    prefix: ["動詞使役形"],
    memorized: false,
    page: 257,
  },
  {
    id: 178,
    grammar: "〜（さ）せられる",
    meaning: "被迫～",
    example_jp: "親に家事の手伝いをさせられた。",
    example_zh: "被父母要求幫忙了家事。",
    prefix: ["動詞使役受身形"],
    memorized: false,
    page: 258,
    supplement: "含有不情願、受害的心情",
  },
  {
    id: 179,
    grammar: "〜でございます",
    meaning: "[鄭重] です",
    example_jp: "じゃ、お客様でございます。",
    example_zh: "那您就是客人了。",
    prefix: ["名詞"],
    memorized: false,
    page: 258,
  },
  {
    id: 180,
    grammar: "〜お（ご）〜になる",
    meaning: "[尊敬] （對方的動作）",
    example_jp: "先生はもう駅にお向かいになりました。",
    example_zh: "老師已經往車站走了。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 260,
    supplement: "1. 其他動詞：お〜になる\n2. サ行變格：ご〜になる",
  },
  {
    id: 181,
    grammar: "〜お（ご）〜する",
    meaning: "[謙讓] （我的動作）",
    example_jp: "お手伝いしましょうか。",
    example_zh: "讓我來幫您吧。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 260,
    supplement: "1. 其他動詞：お〜する\n2. サ行變格：ご〜する",
  },
  {
    id: 182,
    grammar: "〜お（ご）〜いたす",
    meaning: "[謙讓] （我的動作）",
    example_jp: "お手伝いいたしましょうか。",
    example_zh: "讓我來幫您吧。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 260,
    supplement: "比 お（ご）〜する 更謙讓",
  },
  {
    id: 183,
    grammar: "〜お（ご）〜ください",
    meaning: "[尊敬] 請～",
    example_jp: "ここでお待ちください。",
    example_zh: "請在這裡等候。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 262,
    supplement: "1. 其他動詞：お〜ください\n2. サ行變格：ご〜ください",
  },
  {
    id: 184,
    grammar: "〜（さ）せてください",
    meaning: "[尊敬] 請允許我做～",
    example_jp: "お父さん、私をあの人と結婚させてください。",
    example_zh: "爸爸，請讓我跟他結婚。",
    prefix: ["動詞使役形"],
    memorized: false,
    page: 263,
  },
  {
    id: 185,
    grammar: "〜（の）うちに",
    meaning: "趁著～",
    example_jp:
      "元気なうちに、やりたいことを全部やっておこうと思います。趁還很有活力時，我想要去做所有想做的事情。",
    example_zh: "",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 270,
  },
  {
    id: 186,
    grammar: "〜（の）さい",
    meaning: "～的當時",
    example_jp: "東京でお会いした際、名刺をお渡ししたと思うます。",
    example_zh: "我想跟您在東京見面時，有遞過名片給您。",
    prefix: ["動詞た形", "動詞辭書形", "名詞"],
    memorized: false,
    page: 271,
  },
  {
    id: 187,
    grammar: "〜ところだ",
    meaning: "正在～時",
    example_jp: "今、そちらに向かっているところです。我現在正在前往您那裡。",
    example_zh: "",
    prefix: ["動詞た形", "動詞辭書形"],
    memorized: false,
    page: 271,
    supplement:
      "V（連體形）＋ところだ 表示準備要進行的動作。\nV（テ形）＋いる＋ところだ 表示正在進行的動作。\nV（タ形）＋ところだ 表示剛完成不久的動作。\nV（テ形）＋いた＋ところだ 表示直到說話前在進行的動作。",
  },
  {
    id: 188,
    grammar: "〜（の）さいちゅう（に）",
    meaning: "〜正在～時",
    example_jp: "例の件については、今検討している最中だ。",
    example_zh: "那個案子，現在正在檢討中。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 271,
  },
  {
    id: 189,
    grammar: "〜とたん（に）",
    meaning: "～剛～就",
    example_jp: "歌手がステージに出て来たん途端に、地震が起きた。",
    example_zh: "歌手才剛上台，就發生地震了。",
    prefix: ["動詞た形"],
    memorized: false,
    page: 272,
    supplement: "前項動作剛完成的瞬間，就有了後項變化，伴有意外語感。",
  },
  {
    id: 190,
    grammar: "〜いらい",
    meaning: "〜自～以來",
    example_jp: "手術をして以来、ずっと調子がいい。",
    example_zh: "完成手術後，身體狀況一直很好。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 273,
  },
  {
    id: 191,
    grammar: "〜（の）おかげだ",
    meaning: "托您的福",
    example_jp: "それもこれも、先生のおかげです。",
    example_zh: "這個也好、那個也好，都是託老師的福。",
    prefix: ["動詞た形", "名詞", "形容詞"],
    memorized: false,
    page: 278,
  },
  {
    id: 192,
    grammar: "〜によって（は）／による／により",
    meaning: "1. 以～為手段、方法\n2. 根據～\n3. 由於～",
    example_jp: "実例によって、やり方を示す。",
    example_zh: "以實際的例子，演示操作的方法。",
    prefix: ["名詞"],
    memorized: false,
    page: 280,
    supplement: "により 比 によって 正式，修飾整句",
  },
  {
    id: 193,
    grammar: "〜（の）せいか",
    meaning: "（壞事）可能是因為～吧",
    example_jp: "物価が上がってせいか、生活が苦しいです。",
    example_zh: "也許是因為物價上漲，生活才會這麼困苦。",
    prefix: ["動詞た形", "動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 279,
  },
  {
    id: 194,
    grammar: "〜ものだから／もので",
    meaning: "正是因為～所以",
    example_jp: "足が痺れたものだから、立てませんでした。",
    example_zh: "因為腳麻，所以站不起來。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 281,
    supplement: "表達事態嚴重，因此做了某事，不是自己願意的語氣。",
  },
  {
    id: 195,
    grammar: "〜（の）おそれがある",
    meaning: "恐怕會～",
    example_jp: "それが燃やすと、悪いガスが出る恐れがある。",
    example_zh: "那個一燃燒，恐怕會產生不好的氣體。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 286,
  },
  {
    id: 196,
    grammar: "〜にきまっている",
    meaning: "～肯定是這樣",
    example_jp:
      "私だって、結婚したいに決まっているじゃありませんか。ただ、相手がいないだけです。",
    example_zh: "我也是想結婚的啊，但就沒對象啊。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 287,
    supplement: "表達很有信心的推測",
  },
  {
    id: 197,
    grammar: "〜よりない／よりしかたがない／よりほかない",
    meaning: "只能～",
    example_jp: "こうなったら一生懸命やるよりない。",
    example_zh: "事到如今，也只能拼命去做了。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 288,
    supplement: "表達除此之外沒有其他辦法",
  },
  {
    id: 198,
    grammar: "〜にちがいがない",
    meaning: "一定是～不會錯的",
    example_jp: "この写真は、ハワイで撮影されたに違いがない。",
    example_zh: "這張照片一定是在夏威夷拍的。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 288,
  },
  {
    id: 199,
    grammar: "〜（の）ではないだろうか",
    meaning: "不就是～嗎",
    example_jp: "",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 289,
  },
  {
    id: 200,
    grammar: "〜ないかとおもう",
    meaning: "我想是～吧",
    example_jp: "彼は誰もよりも君を愛していたのではないかと思う。",
    example_zh: "我想他比誰都更愛你吧。",
    prefix: ["動詞否定形", "形容詞"],
    memorized: false,
    page: 289,
  },
  {
    id: 201,
    grammar: "〜（の）わけだ",
    meaning: "難怪～",
    example_jp: "あ、賞味期限が切られている。美味しくないわけだ。",
    example_zh: "原來過了賞味期限，難怪不好吃。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 290,
  },
  {
    id: 202,
    grammar: "〜（の）わけがない／わけはない",
    meaning: "不可能～",
    example_jp: "こんな簡単なことをできないわけがない。",
    example_zh: "這麼簡單的事，不可能做不到。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 295,
  },
  {
    id: 203,
    grammar: "〜わけではない／わけでもない",
    meaning: "並不是～",
    example_jp: "喧嘩ばかりしていても、互いに嫌っているわけでもない。",
    example_zh: "老是吵架，也不代表彼此互相討厭。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 296,
  },
  {
    id: 204,
    grammar: "〜（な）んじゃない／んじゃないかとおもう",
    meaning: "～不是嗎？",
    example_jp: "彼はもう帰ったんじゃない。",
    example_zh: "他已經回去了吧。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 297,
    supplement: "口語形",
  },
  {
    id: 205,
    grammar: "〜かける",
    meaning: "才剛開始～",
    example_jp: "メールを書きかけた時、電話が鳴った。",
    example_zh: "才剛寫電子郵件，電話就響了。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 301,
    supplement: "表行為已經開始，但還沒結束。",
  },
  {
    id: 206,
    grammar: "〜がち",
    meaning: "～傾向於",
    example_jp: "子供は、ゲームに熱中しがちです。",
    example_zh: "",
    prefix: ["動詞ます形", "名詞"],
    memorized: false,
    page: 302,
    supplement: "負面評價",
  },
  {
    id: 207,
    grammar: "〜ぎみ",
    meaning: "感覺有點～",
    example_jp: "疲れぎみなので、もう寝ます。",
    example_zh: "我有點累，要去睡了。",
    prefix: ["動詞て形", "名詞"],
    memorized: false,
    page: 302,
    supplement: "表示當下主觀感受",
  },
  {
    id: 208,
    grammar: "〜だらけ",
    meaning: "到處是～",
    example_jp: "あの人は借金だらけだ。",
    example_zh: "那個人欠了一屁股債。",
    prefix: ["名詞"],
    memorized: false,
    page: 303,
    supplement: "負面評價",
  },
  {
    id: 209,
    grammar: "〜むき",
    meaning: "（本質上）面向、適合～",
    example_jp: "南向きの部屋は暖かくて明るいです。",
    example_zh: "朝南的房子又暖採光又好。",
    prefix: ["名詞"],
    memorized: false,
    page: 307,
  },
  {
    id: 210,
    grammar: "〜むけ",
    meaning: "（設計得）針對～",
    example_jp: "小説家ですが、たまに子供向けの童話も書きます。",
    example_zh: "雖然是小說家，偶爾也會寫針對小孩的童書。",
    prefix: ["名詞"],
    memorized: false,
    page: 307,
  },
  {
    id: 211,
    grammar: "〜くらい",
    meaning: "～的程度",
    example_jp: "彼と一緒になった時は、嬉して涙が出るくらいでした。",
    example_zh: "跟他結婚時，高興到眼淚要掉下來的程度。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 311,
  },
  {
    id: 212,
    grammar: "〜ば〜ほど",
    meaning: "越～越～",
    example_jp: "字は、練習すれば練習するほど、きれいに書けるようになります。",
    example_zh: "字會越練越漂亮。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 312,
  },
  {
    id: 213,
    grammar: "〜どおり",
    meaning: "正如〜",
    example_jp: "結果は、予想どおりだった。",
    example_zh: "結果跟預想的一樣。",
    prefix: ["名詞"],
    memorized: false,
    page: 318,
  },
  {
    id: 214,
    grammar: "〜をもとに（して）",
    meaning: "以～為參考、啟示～",
    example_jp: "彼女のデザインをもとに、ワンピースを作った。",
    example_zh: "以她的設計爲參考，做了連身裙。",
    prefix: ["名詞"],
    memorized: false,
    page: 318,
    supplement: "後者可能跟前者差很多，僅以前者作爲參考、發想",
  },
  {
    id: 215,
    grammar: "〜にともなって",
    meaning: "隨著～（因此產生變化）",
    example_jp: "この物質は、温度の変化に伴って色が変わります。",
    example_zh: "這物質的顏色會隨著溫度而變。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 320,
  },
  {
    id: 216,
    grammar: "〜とともに",
    meaning: "隨著～",
    example_jp: "物価の変動とともに、消費の傾向が変化する。",
    example_zh: "隨著物價的變動，消費趨勢會變化。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 319,
    supplement: "後項隨著前項同時發生",
  },
  {
    id: 217,
    grammar: "〜につれて",
    meaning: "隨著～（同時變化）",
    example_jp: "勉強するにつれて、化学の面白さがわかっていた。",
    example_zh: "隨著學習，越來越能了解化學的有趣之處了。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 319,
  },
  {
    id: 218,
    grammar: "〜からいうと／いって",
    meaning: "從～來看",
    example_jp: "栄養の観点からいうと、こちらの弁当の方がいいと思います。",
    example_zh: "從營養的觀點來看，我覺得這個便當比較好。",
    prefix: ["名詞"],
    memorized: false,
    page: 323,
  },
  {
    id: 219,
    grammar: "〜としたら／とすると／とすれば",
    meaning: "如果～",
    example_jp: "毎日が休日だとしたら、何がしたい？",
    example_zh: "假設每天都是假日，你想做什麼？",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 325,
    supplement:
      "• としたら：以前項為前提，判斷或評價\n  • たら：如果前項成立，後項會實現",
  },
  {
    id: 220,
    grammar: "〜にかんして",
    meaning: "～關於",
    example_jp: "事件に関しての情報。（＝事件に関する情報）",
    example_zh: "跟事件有關的情報。",
    prefix: ["名詞"],
    memorized: false,
    page: 325,
  },
  {
    id: 221,
    grammar: "〜にとって",
    meaning: "對～來說",
    example_jp: "この写真は姉にとって大切なものです。",
    example_zh: "這張照片對姊姊來說很重要。",
    prefix: ["名詞"],
    memorized: false,
    page: 327,
  },
  {
    id: 222,
    grammar: "〜にもとづいて",
    meaning: "以～為根據",
    example_jp: "違反者は法律に基づいて処罰されます。",
    example_zh: "違者依法處罰。",
    prefix: ["名詞"],
    memorized: false,
    page: 332,
    supplement: "後者不會偏離前者",
  },
  {
    id: 223,
    grammar: "〜をちゅうしんに（して）",
    meaning: "以～為中心",
    example_jp: "彼は環境問題を中心にして研究しようと思っています。",
    example_zh: "他想將環境問題作為研究的重點。",
    prefix: ["名詞"],
    memorized: false,
    page: 334,
  },
  {
    id: 224,
    grammar: "〜をとおして／をつうじて",
    meaning: "1. 透過\n  2. 在整個期間",
    example_jp: "SNSを通じて、彼女と知り合った。透過社交平台，認識了女友。",
    example_zh: "高雄は一年を通じて暑いです。",
    prefix: ["名詞"],
    memorized: false,
    page: 335,
    supplement: "つうじて比較正式，較被動偶然",
  },
  {
    id: 225,
    grammar: "〜（の）かわりに",
    meaning: "代替～",
    example_jp: "パソコンの代わりにiPadを使います。",
    example_zh: "使用iPad取代電腦。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 336,
  },
  {
    id: 226,
    grammar: "〜もの／もん",
    meaning: "因為～嘛",
    example_jp: "僕は悪くない。先に叩いてきたのは、あいつだもん。",
    example_zh: "不是我的錯，是他先打過來的。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 346,
    supplement:
      "表示原因理由，屬於較隨便的口語，通常用於主張自己行為的合理性，多有辯解的意味。",
  },
  {
    id: 227,
    grammar: "〜てたまらない",
    meaning: "～得受不了",
    example_jp: "北海道は寒くてたまらない。",
    example_zh: "北海道冷得受不了。",
    prefix: ["形容詞"],
    memorized: false,
    page: 347,
  },
  {
    id: 228,
    grammar: "〜てならない",
    meaning: "～不禁",
    example_jp: "ピーマンを食べるのが嫌でならない。",
    example_zh: "我特別討厭吃青椒。",
    prefix: ["動詞て形", "名詞", "形容詞"],
    memorized: false,
    page: 347,
    supplement: "表情感上的受不了",
  },
  {
    id: 229,
    grammar: "〜をこめて",
    meaning: "傾注（感情）～",
    example_jp: "心を込めて一つ一つ手作りする。",
    example_zh: "真心誠意地一個一個親手製作。",
    prefix: ["名詞"],
    memorized: false,
    page: 348,
  },
  {
    id: 230,
    grammar: "〜ようがない",
    meaning: "完全無法～",
    example_jp: "人との関係は一度こじれたら、修復しようがない。",
    example_zh: "和人的關係一旦惡化了，就無法修復了。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 353,
  },
  {
    id: 231,
    grammar: "〜さえ〜ば",
    meaning: "只要～就夠了",
    example_jp: "やる気さえあれば、年齢や経験など一切は問いません。",
    example_zh: "只要有幹勁，年齡經驗一切都沒有要求。",
    prefix: ["動詞て形", "動詞ます形", "名詞"],
    memorized: false,
    page: 358,
  },
  {
    id: 232,
    grammar: "たとえ〜ても〜",
    meaning: "即使、哪怕",
    example_jp: "たとえ相手が親友でも、最低限の礼儀は必要だ。",
    example_zh: "即使對方是摯友，也需要最低限度的禮節。",
    prefix: ["句首"],
    memorized: false,
    page: 359,
  },
  {
    id: 233,
    grammar: "〜てくる",
    meaning: "表距離由遠而近、表動作後會再回來、表狀態顯現⋯⋯",
    example_jp: "バスがやってきました。",
    example_zh: "公車朝這裡開過來了。",
    prefix: ["動詞て形"],
    memorized: false,
  },
  {
    id: 234,
    grammar: "〜てからでないと／てからでなければ",
    meaning: "不先（做前項）就不能（做後項）",
    example_jp: "宿題をしてからでないと、遊びに行けない。",
    example_zh: "不先完成作業就不能去玩。",
    prefix: ["動詞て形"],
    memorized: false,
    page: 360,
  },
  {
    id: 235,
    grammar: "〜ことにしている",
    meaning: "都會～",
    example_jp: "夜は勉強することにしている。",
    example_zh: "我晚上都會念書。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 367,
    supplement:
      "「ことにしている」是由「決定（ことにする）」而衍生的習慣，\n「ようにする」則是「期許能達成（できるだけするように）」而養成的習慣。",
  },
  {
    id: 236,
    grammar: "〜ことになっている",
    meaning: "按規定～",
    example_jp: "日本では、車は左側を走ることになっている。",
    example_zh: "在日本，車子是左側行駛的。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 368,
    supplement: "表示這項內容是已經成立的常規狀態。",
  },
  {
    id: 237,
    grammar: "〜にくわえて",
    meaning: "加上～",
    example_jp: "能力に加えて、人柄も重視されます。",
    example_zh: "能力以外，也很重視人品。",
    prefix: ["名詞"],
    memorized: false,
    page: 375,
  },
  {
    id: 238,
    grammar: "〜とか",
    meaning: "1. 之類～\n  2. 好像是～",
    example_jp: "隣の奥さんは浮気したとかで、離婚した。",
    example_zh:
      "→隔壁的太太因為偷吃還是怎樣的，離婚了。—— 因為……，我也不確定原因",
    prefix: ["名詞"],
    memorized: false,
    page: 374,
    supplement: "表示「內容不確定，有些是聽說的，我自己也不清楚」",
  },
  {
    id: 239,
    grammar: "〜っけ",
    meaning: "是不是～來著",
    example_jp: "去年のこの時期、同じくらい寒かったっけ？",
    example_zh: "去年的這個時候，一樣這麼冷來著嗎？",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 374,
  },
  {
    id: 240,
    grammar: "〜をはじめ",
    meaning: "以～為首",
    example_jp: "彼はこの絵をはじめ、素晴らしい作品をたくさん残した。",
    example_zh: "他除了這幅畫之外，還留下很多傑出的作品。",
    prefix: ["名詞"],
    memorized: false,
    page: 379,
  },
  {
    id: 241,
    grammar: "〜（の）くせに",
    meaning: "明明～卻～",
    example_jp: "あいつは頭が悪いくせに、頭のいい振りをしている。",
    example_zh: "那傢伙明明很笨，卻裝作很聰明。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 384,
    supplement: "帶有譴責、不滿、輕蔑語氣",
  },
  {
    id: 242,
    grammar: "〜くらいなら",
    meaning: "與其～不如～",
    example_jp: "あんな店で高いお金を払うぐらいなら、自分で作った方がましだ。",
    example_zh: "與其在那種店付高額費用，不如自己做還比較好。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 385,
    supplement: "後句常跟「まし」搭配。",
  },
  {
    id: 243,
    grammar: "〜としても",
    meaning: "即使～也～",
    example_jp: "これが本物の宝石だとしても、私は買いません。",
    example_zh: "",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 385,
  },
  {
    id: 244,
    grammar: "〜にはんして",
    meaning: "與～相反",
    example_jp: "予想に反して、彼は金メダルを獲得した。",
    example_zh: "與預期相反，他獲得了金牌。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 389,
  },
  {
    id: 245,
    grammar: "〜（である）はんめん",
    meaning: "另一方面～",
    example_jp: "自然を満喫できる旅館である反面、交通の便は良くない。",
    example_zh: "雖然是能夠享受大自然的旅館，但另一方面交通很不方便。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 390,
  },
  {
    id: 246,
    grammar: "〜って",
    meaning: "某人說～",
    example_jp: "北条さんはまだ独身なんだって。",
    example_zh: "聽說北条還是單身。",
    prefix: ["名詞"],
    memorized: false,
    page: 405,
    supplement:
      "1. 「んだって」表示聽來的消息\n  2. 「って」直接引述某人講的話",
  },
  {
    id: 247,
    grammar: "〜から〜にかけて",
    meaning: "從～到",
    example_jp: "北部から中部にかけて大雪となっています。",
    example_zh: "從北部到中部下起了大雪。",
    prefix: ["名詞"],
    memorized: false,
    page: 423,
    supplement:
      "から～まで 強調動作始末\nから〜にかけて 則只是表達橫跨兩端時間或空間",
  },
  {
    id: 248,
    grammar: "〜きる",
    meaning: "動作做到極限",
    example_jp: "この小説はとても面白くて、一気に読み切った。",
    example_zh: "這本小說很有趣，一口氣看完了。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 424,
    supplement: "複合動詞",
  },
  {
    id: 249,
    grammar: "〜にわたる",
    meaning: "長達～",
    example_jp: "電車が2時間にわたり停車した。",
    example_zh: "電車停駛長達2小時。",
    prefix: ["名詞"],
    memorized: false,
    page: 433,
  },
  {
    id: 250,
    grammar: "〜めぐって",
    meaning: "～圍繞著",
    example_jp: "世界一の称号を巡り、今年も世界の強豪たちが一堂に集結した。",
    example_zh: "圍繞著世界第一的稱號，今年世界的強隊們也齊聚一堂。",
    prefix: ["名詞"],
    memorized: false,
    page: 442,
  },
  {
    id: 251,
    grammar: "〜におうじて",
    meaning: "順應～而動作",
    example_jp: "季節に応じて、服装を選ぶ必要があります。",
    example_zh: "需要根據季節來選擇服裝。",
    prefix: ["名詞"],
    memorized: false,
    page: 443,
  },
  {
    id: 252,
    grammar: "〜にかけては",
    meaning: "～至少在這方面",
    example_jp: "営業にかけては、彼の右に出る者はいない。",
    example_zh: "在銷售方面，沒有人能超過他。",
    prefix: ["名詞"],
    memorized: false,
    page: 444,
    supplement: "表示「其他姑且不論，至少這方面來說」，後面多接讚賞",
  },
  {
    id: 253,
    grammar: "〜にこたえて",
    meaning: "回應～",
    example_jp: "市民のリクエストに応えて、新しい公園が作られた。",
    example_zh: "為了回應市民的呼聲，一個新公園建成了。",
    prefix: ["名詞"],
    memorized: false,
    page: 445,
  },
  {
    id: 254,
    grammar: "〜にそって",
    meaning: "沿著～",
    example_jp: "手順に沿って、作業を進めてください。",
    example_zh: "請依照步驟進行操作。",
    prefix: ["名詞"],
    memorized: false,
    page: 448,
  },
  {
    id: 255,
    grammar: "〜からして",
    meaning: "從～來看",
    example_jp: "あのレストランは、サービスからして良くない。",
    example_zh: "那家餐廳光是服務就不好。",
    prefix: ["名詞"],
    memorized: false,
    page: 449,
    supplement: "表達以某個範例為依據對整體做出判斷或評價",
  },
  {
    id: 256,
    grammar: "〜からといって",
    meaning: "不能只因為～就",
    example_jp: "彼が言ったからといって、それが正しいとは限らない。",
    example_zh: "不能因為是他說的就認為那是對的。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 449,
  },
  {
    id: 257,
    grammar: "〜からすれば／からすると",
    meaning: "從～來看",
    example_jp: "彼の表情からすると、あまり興味がないようだ。",
    example_zh: "從他的表情來看，他似乎不太感興趣。",
    prefix: ["名詞"],
    memorized: false,
    page: 450,
  },
  {
    id: 258,
    grammar: "〜からみれば／からみると",
    meaning: "從～來看",
    example_jp: "この絵から見ると、彼は非常に才能があるようだ。",
    example_zh: "從這幅畫可以看出他好像很有天份。",
    prefix: ["名詞"],
    memorized: false,
    page: 451,
  },
  {
    id: 259,
    grammar: "〜（の）うえ（で）",
    meaning: "在～之後",
    example_jp: "よく考えた上で、やはり留学することにした。",
    example_zh: "經過深思熟慮之後，決定還是去留學。",
    prefix: ["動詞た形", "名詞"],
    memorized: false,
    page: 455,
  },
  {
    id: 260,
    grammar: "〜（の）すえ（に）",
    meaning: "結果",
    example_jp: "長時間の作業の末、やっと完了しました。",
    example_zh: "經過很長的作業時間，終於完成了。",
    prefix: ["動詞た形", "名詞"],
    memorized: false,
    page: 455,
    supplement: "表花了很多時間，有了最後結果。書面語。",
  },
  {
    id: 261,
    grammar: "〜につけ（て）",
    meaning: "每當～就～（感覺）",
    example_jp: "写真を見るにつけ、あの頃を思い出す。",
    example_zh: "每當看到這些照片，我就會想起那段時光。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 457,
  },
  {
    id: 262,
    grammar: "〜にさきだち",
    meaning: "在～之前，先～",
    example_jp: "新製品の発売に先立って、記者会見が開かれた。",
    example_zh: "新產品發布之前，召開了記者招待會。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 457,
  },
  {
    id: 263,
    grammar: "〜ないうちに",
    meaning: "趁著還沒～",
    example_jp: "雷だ。降り出さないうちに、早く帰ろう。",
    example_zh: "打雷了，趁著還沒下雨，快回家吧。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 458,
  },
  {
    id: 264,
    grammar: "〜（の）あげく（に）",
    meaning: "經過～到最後（負面）",
    example_jp:
      "何杯もラーメンを食べたあげく（に）、お腹いっぱいで吐いてしまった。",
    example_zh: "吃了好幾碗拉麵，結果肚子太撐全部吐出來了。",
    prefix: ["動詞た形", "名詞"],
    memorized: false,
    page: 461,
    supplement: "多用在負面結果",
  },
  {
    id: 265,
    grammar: "〜か〜ないかのうちに",
    meaning: "才剛～就",
    example_jp: "電話が鳴るか鳴らないかのうちに、彼女が受話器を取った。",
    example_zh: "電話鈴聲一響，她就拿起聽筒了。",
    prefix: ["動詞た形", "動詞辭書形"],
    memorized: false,
    page: 462,
    supplement: "表達兩個事件幾乎同時發生",
  },
  {
    id: 266,
    grammar: "〜ときたら",
    meaning: "說到～（＋責怪、不滿）",
    example_jp:
      "あのレストランときたら、高いし、まずいし、もう二度と行かない。",
    example_zh: "提到那家餐廳，又貴又不好吃，再也不要去。",
    prefix: ["名詞"],
    memorized: false,
    page: 481,
  },
  {
    id: 267,
    grammar: "〜（か）とおもうと／とおもったら",
    meaning: "剛～就～",
    example_jp: "新しい社員が入社したかと思ったら、もう辞めてしまった。",
    example_zh: "新進員工才剛入職，馬上就辭職了。",
    prefix: ["動詞た形"],
    memorized: false,
    page: 481,
  },
  {
    id: 268,
    grammar: "〜ものなら",
    meaning: "要是能～的話",
    example_jp: "時間が戻せるものなら、もう一度やり直したい。",
    example_zh: "如果能回到過去，我想重新開始。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 482,
    supplement: "帶有誇張語氣，表達難以實現的假設",
  },
  {
    id: 269,
    grammar: "〜ないかぎり",
    meaning: "若不～就不能～",
    example_jp: "予約をしない限り、席は確保できません。",
    example_zh: "不預約就無法確保座位。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 483,
    supplement: "如果不滿足某個條件，某件事就無法實現。",
  },
  {
    id: 270,
    grammar: "〜ないことには",
    meaning: "如果不～就無法～",
    example_jp: "彼が来ないことには、会議を始められない。",
    example_zh: "他不來，我們就無法開始會議。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 487,
  },
  {
    id: 271,
    grammar: "〜ぬきで／はぬきにして",
    meaning: "省去～",
    example_jp: "挨拶は抜きにして、本題に入りましょう。",
    example_zh: "不用客套了，直接進入正題吧。",
    prefix: ["名詞"],
    memorized: false,
    page: 488,
  },
  {
    id: 272,
    grammar: "〜をきっかけに",
    meaning: "以～為契機",
    example_jp: "友人の勧めをきっかけとして、彼はランニングを始めた。",
    example_zh: "朋友的建議促使他開始跑步運動。",
    prefix: ["名詞"],
    memorized: false,
    page: 489,
  },
  {
    id: 273,
    grammar: "〜をけいきに",
    meaning: "以～為契機",
    example_jp: "転職を契機として、新しい分野に挑戦することにしました。",
    example_zh: "以換工作為契機，我決定挑戰新的領域。",
    prefix: ["名詞"],
    memorized: false,
    page: 490,
    supplement: "較書面語",
  },
  {
    id: 274,
    grammar: "〜うえは",
    meaning: "既然～",
    example_jp: "約束した上は、何が何でも守りなさい。",
    example_zh: "既然答應了，就無輪如何都要遵守。",
    prefix: ["動詞た形", "動詞辭書形"],
    memorized: false,
    page: 469,
  },
  {
    id: 275,
    grammar: "〜（の）かぎり",
    meaning: "〜在範圍內",
    example_jp: "私ができる限り、あなたをサポートします。",
    example_zh: "只要我做得到的話，我就會一直支持你。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 468,
  },
  {
    id: 276,
    grammar: "〜（の）うえ（に）",
    meaning: "不僅～而且",
    example_jp: "兄は無職である上にギャンブルが好きだから、心配でたまらない。",
    example_zh: "哥哥沒有在工作，而且還喜歡賭博，真令人擔心。",
    prefix: ["名詞", "形容詞"],
    memorized: false,
    page: 469,
  },
  {
    id: 277,
    grammar: "〜（の）ことだから",
    meaning: "以～來說～（判斷）",
    example_jp: "彼のことだから、こんな問題はすぐに解決するだろう。",
    example_zh: "以他的能力，這種問題應該很快就能解決。",
    prefix: ["名詞"],
    memorized: false,
    page: 470,
  },
  {
    id: 278,
    grammar: "〜あまり（に）",
    meaning: "因為過於～",
    example_jp: "面接前、緊張のあまり（に）、足が動かなかった。",
    example_zh: "面試之前，由於太過緊張，雙腳動彈不得。",
    prefix: ["動詞た形", "動詞辭書形", "名詞"],
    memorized: false,
    page: 470,
  },
  {
    id: 279,
    grammar: "〜だけに",
    meaning: "～正因為",
    example_jp: "信じていただけに、裏切られた時はショックだった。",
    example_zh: "正因為太相信了，被他背叛時尤其震驚。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 471,
  },
  {
    id: 280,
    grammar: "〜ことから",
    meaning: "1. 從～來看\n  2. 因為～",
    example_jp: "その曲は年間で一番再生されたことから、最優秀賞を受賞した。",
    example_zh: "這首歌是今年播放最多的歌曲，所以獲得了最優秀獎。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 474,
  },
  {
    id: 281,
    grammar: "〜せいで",
    meaning: "都怪～",
    example_jp: "失敗したのは無能な味方のせいだ。",
    example_zh: "會失敗是因為無能的隊友害的。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 474,
  },
  {
    id: 282,
    grammar: "〜にしても",
    meaning: "就算～也～",
    example_jp: "この問題はいくら難しいにしても、解決しなければならない。",
    example_zh: "不論這個問題有多難，都必須解決。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 497,
    supplement: "提出極端的假設條件，並表達意見或評價",
  },
  {
    id: 283,
    grammar: "〜ながら（に／も）",
    meaning: "雖然～，但是～",
    example_jp: "残念ながら、私は参加できません。",
    example_zh: "雖然很遺憾，但是我不能參加。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 494,
  },
  {
    id: 284,
    grammar: "〜どころか",
    meaning: "非但沒有～還～",
    example_jp: "雨が止むどころか、ますます激しくなってきた。",
    example_zh: "雨不但沒有停，反而越來越大了。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 494,
    supplement: "強調情況繼續惡化",
  },
  {
    id: 285,
    grammar: "〜ものの",
    meaning: "雖然～，但是～",
    example_jp:
      "台湾では大学を出たものの、就職ができずアルバイトをする人が多い。",
    example_zh: "在台灣，雖然大學畢業了，但是很多人沒有辦法順利就職而去打工。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 495,
  },
  {
    id: 286,
    grammar: "〜とはいえ",
    meaning: "雖說～但～",
    example_jp: "彼は若いとはいえ、仕事の経験が豊富だ。",
    example_zh: "他雖然年輕，但工作經驗豐富。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 495,
    supplement: "表達不完全贊同",
  },
  {
    id: 287,
    grammar: "〜にしろ",
    meaning: "就算～",
    example_jp: "遅れるにしろ、連絡だけはしてください。",
    example_zh: "就算遲到了，也請至少通知我一下。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 501,
    supplement: "極端的假設條件，並表達意見或評價",
  },
  {
    id: 288,
    grammar: "〜にかかわらず",
    meaning: "無論～都～",
    example_jp: "するかしないかに関わらず",
    example_zh: "不管做不做",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 501,
  },
  {
    id: 289,
    grammar: "〜にもかかわらず",
    meaning: "雖然～但是",
    example_jp: "雨にもかかわらず、彼は傘を持たずに出かけた。",
    example_zh: "下雨，卻沒帶傘就出門。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 503,
    supplement: "類似「のに」",
  },
  {
    id: 290,
    grammar: "〜にせよ",
    meaning: "就算～",
    example_jp: "どういう状況であるにせよ、説明は必要じゃない？",
    example_zh: "不管發生了什麼，難道不需要說明嗎？",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 502,
  },
  {
    id: 291,
    grammar: "〜にしては",
    meaning: "以～來說，算～",
    example_jp: "この本、中古かな？中古にしてはきれいだね。",
    example_zh: "這本書，是二手書吧？以二手書而言，算是乾淨的呢。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 502,
    supplement: "事實與說話者抱持的評價、期待相差很大時使用。",
  },
  {
    id: 292,
    grammar: "〜だけあって／〜だけのことはある",
    meaning: "不愧是～",
    example_jp: "彼はプロの料理人だけありますね。",
    example_zh: "他不愧是專業廚師。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 503,
  },
  {
    id: 293,
    grammar: "〜もかまわず",
    meaning: "無視～，就～",
    example_jp: "彼女は人目も構わず、泣き出した。",
    example_zh: "她不顧他人的眼光，哭了起來。",
    prefix: ["名詞"],
    memorized: false,
    page: 504,
  },
  {
    id: 294,
    grammar: "〜ことなく",
    meaning: "沒有～就～",
    example_jp: "彼は一度も振り返ることなく、前に進んで行った。",
    example_zh: "他一直向前走，沒有回頭。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 507,
  },
  {
    id: 295,
    grammar: "〜きり〜ない",
    meaning: "從那時起就不再～",
    example_jp: "彼は海外出張に行ったきり、戻ってこない。",
    example_zh: "他出國出差後，就沒有回來過。",
    prefix: ["動詞た形"],
    memorized: false,
    page: 508,
    supplement: "表示某個事情發生後，就一直是同一個狀態",
  },
  {
    id: 296,
    grammar: "〜つつ",
    meaning: "1. 一邊～一邊～\n  2. 雖然～但是～",
    example_jp: "彼女は将来を考えつつ、現在の仕事に専念している。",
    example_zh: "她一邊思考未來，一邊專注於現在的工作。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 510,
  },
  {
    id: 297,
    grammar: "〜やら〜やら",
    meaning: "又是～、又是～",
    example_jp: "勉強するやら、アルバイトをするやらで忙しい。",
    example_zh: "學習、打工什麼的，忙得不可開交。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 516,
    supplement: "多有心情不快的語感",
  },
  {
    id: 298,
    grammar: "〜も〜ば／なら〜も",
    meaning: "不僅～又～",
    example_jp: "あのレストランは値段も手頃なら、料理も美味しい。",
    example_zh: "那家餐廳不僅價錢公道、又很好吃。",
    prefix: ["動詞ば形", "名詞", "形容詞"],
    memorized: false,
    page: 517,
    supplement: "強調各種情況都有",
  },
  {
    id: 299,
    grammar: "〜にかぎって",
    meaning: "唯獨～",
    example_jp: "彼に限って、そんなミスをするはずがない。",
    example_zh: "他絕對不會犯這種錯誤。",
    prefix: ["名詞"],
    memorized: false,
    page: 520,
  },
  {
    id: 300,
    grammar: "〜のみならず",
    meaning: "不只～而且～",
    example_jp: "彼女は歌が上手いのみならず、ダンスも得意だ。",
    example_zh: "她不但唱得好，而且舞也跳得好。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 524,
  },
  {
    id: 301,
    grammar: "〜（數量詞）ばかり",
    meaning: "大約～",
    example_jp: "料理はまだ半分ばかり残っている。",
    example_zh: "料理還剩下大約一半。",
    prefix: ["名詞"],
    memorized: false,
    page: 526,
  },
  {
    id: 302,
    grammar: "〜はともかく",
    meaning: "姑且不管～",
    example_jp: "結果はともかく、まずは努力することが大事だ。",
    example_zh: "結果暫且不論，首先重要的是努力。",
    prefix: ["名詞"],
    memorized: false,
    page: 533,
  },
  {
    id: 303,
    grammar: "〜をとわず",
    meaning: "無論～",
    example_jp: "年齢に関わらず、誰でも入れます。",
    example_zh: "不論年齡，誰都可以進去。",
    prefix: ["名詞"],
    memorized: false,
    page: 533,
  },
  {
    id: 304,
    grammar: "〜にかわって",
    meaning: "代替～",
    example_jp: "先輩に代わって、私があいさつします。",
    example_zh: "我代替前輩來向您問候。",
    prefix: ["名詞"],
    memorized: false,
    page: 535,
  },
  {
    id: 305,
    grammar: "〜のもとで",
    meaning: "在～的影響下",
    example_jp: "両親のもとで、彼は幸せな子供時代を過ごした。",
    example_zh: "在父母的照顧下，他度過了幸福的童年。",
    prefix: ["名詞"],
    memorized: false,
    page: 538,
  },
  {
    id: 306,
    grammar: "〜（の）うえでは",
    meaning: "根據～",
    example_jp: "この二人は、法律の上では夫婦です。",
    example_zh: "這兩個人在法律上是夫妻。",
    prefix: ["名詞"],
    memorized: false,
    page: 540,
  },
  {
    id: 307,
    grammar: "〜まい",
    meaning: "1. 應該不會吧\n  2. 決定不",
    example_jp: "王さんはもうたばこを吸うまい。",
    example_zh: "王先生應該不會再抽菸了。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 542,
  },
  {
    id: 308,
    grammar: "〜というものではない",
    meaning: "並不是～",
    example_jp: "成功は努力すれば必ず手に入るというものではない。",
    example_zh: "僅靠努力並非能成功。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 545,
  },
  {
    id: 309,
    grammar: "〜というしまつだ",
    meaning: "結果竟然～",
    example_jp: "彼は借金を返せず、ついには家を売る始末だ。",
    example_zh: "他還不起債，最後連房子都賣了。",
    prefix: ["動詞辭書形"],
    memorized: false,
    page: 545,
    supplement: "最終導致不良結果",
  },
  {
    id: 310,
    grammar: "〜ようではないか",
    meaning: "我們（一起）～吧",
    example_jp: "明日、みんなで集まろうじゃないか。",
    example_zh: "明天大家一起聚一聚吧。",
    prefix: ["動詞意向形"],
    memorized: false,
    page: 545,
  },
  {
    id: 311,
    grammar: "〜にそういない",
    meaning: "～確定無誤",
    example_jp: "彼女の表情を見る限り、何か隠しているに相違ないです。",
    example_zh: "從她的表情來看，她肯定在隱瞞什麼。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 551,
  },
  {
    id: 312,
    grammar: "〜にほかならない",
    meaning: "完全是～",
    example_jp: "彼の成功は努力の結果にほかならない。",
    example_zh: "他的成功無非是努力的結果。",
    prefix: ["名詞"],
    memorized: false,
    page: 551,
  },
  {
    id: 313,
    grammar: "〜ざるをえない",
    meaning: "不得不～",
    example_jp: "この仕事が終わるまで、残業せざるを得ない。",
    example_zh: "在工作完成之前，我必須加班。",
    prefix: ["動詞否定形"],
    memorized: false,
    page: 552,
  },
  {
    id: 314,
    grammar: "〜うる／える",
    meaning: "可能～",
    example_jp: "彼の言うことは信じ得ません。",
    example_zh: "他的話無法令人相信。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 557,
    supplement: "否定形只能唸えない",
  },
  {
    id: 315,
    grammar: "〜かねない",
    meaning: "可能～（發生不希望的結果）",
    example_jp: "お酒を飲んで運転すると、事故を起こしかねない。",
    example_zh: "喝了酒開車的話，有可能發生事故。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 558,
  },
  {
    id: 316,
    grammar: "〜っこない",
    meaning: "不可能～",
    example_jp: "彼がそんなことをするなんて、信じられっこない。",
    example_zh: "我絕對不相信他會做那樣的事。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 558,
  },
  {
    id: 317,
    grammar: "〜がたい",
    meaning: "難以～",
    example_jp: "彼の行動は理解しがたいです。",
    example_zh: "他的行為難以理解。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 559,
    supplement: "表示該行為難度很高，不能用在表示能力不足時。",
  },
  {
    id: 318,
    grammar: "〜にくい",
    meaning: "～很難",
    example_jp: "会社に行きにくい。",
    example_zh: "（跟上司關係不好，）所以不想去公司。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 560,
    supplement:
      "「～づらい」主要表示「心理性」的困難，而「～にくい」可表示「心理性」，也能表示「物理、環境性」的困難。",
  },
  {
    id: 319,
    grammar: "〜かのようだ",
    meaning: "像～一樣的",
    example_jp: "彼はその事実を知っていたかのように、冷静に対処した。",
    example_zh: "他冷靜地應對，彷彿早就知道真相了。",
    prefix: ["動詞た形", "動詞辭書形"],
    memorized: false,
    page: 565,
    supplement: "表達某事物看起來像某種情況，但實際上並非如此",
  },
  {
    id: 320,
    grammar: "〜（の）ようだ",
    meaning: "好像～",
    example_jp: "あの人は出席するようだ。",
    example_zh: "那個人好像會出席。",
    prefix: ["動詞た形", "動詞辭書形", "名詞"],
    memorized: false,
    page: 565,
    supplement: "依據自身的感覺做的主觀推斷",
  },
  {
    id: 321,
    grammar: "〜げ",
    meaning: "看起來～",
    example_jp: "彼女は心配げに電話を見つめていた。",
    example_zh: "她帶著擔憂的神情盯著手機。",
    prefix: ["動詞ます形", "形容詞"],
    memorized: false,
    page: 566,
    supplement: "表達某種外觀的氣氛",
  },
  {
    id: 322,
    grammar: "〜つつある",
    meaning: "正在～",
    example_jp: "地球の温暖化が進みつつある。",
    example_zh: "地球的溫室效應正在加劇。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 566,
    supplement: "書面語",
  },
  {
    id: 323,
    grammar: "〜（よ）うとしている",
    meaning: "即將要",
    example_jp: "太陽が地平線から登ろう昇ろうとしている。",
    example_zh: "太陽漸漸從地平線升起。",
    prefix: ["動詞意向形"],
    memorized: false,
    page: 567,
    supplement: "表變化即將發生",
  },
  {
    id: 324,
    grammar: "〜にすぎない",
    meaning: "不過是～",
    example_jp: "彼の成功は運が良かったに過ぎないです。",
    example_zh: "他的成功不過是運氣好而已。",
    prefix: ["動詞辭書形", "名詞", "形容詞"],
    memorized: false,
    page: 567,
  },
  {
    id: 325,
    grammar: "〜てしょうがない",
    meaning: "～得不得了",
    example_jp: "試験の結果が心配でしょうがない。",
    example_zh: "我非常擔心考試結果。",
    prefix: ["動詞て形", "形容詞"],
    memorized: false,
    page: 568,
    supplement: "表達某種無法抑制的強烈情緒",
  },
  {
    id: 326,
    grammar: "〜ぬく",
    meaning: "～堅持到底",
    example_jp: "この秘密を死ぬまで守り抜くつもりです。",
    example_zh: "這個秘密到死都會守住。",
    prefix: ["動詞ます形"],
    memorized: false,
    page: 568,
    supplement: "是複合動詞",
  },
  {
    id: 327,
    grammar: "〜どころではない",
    meaning: "現在不是做～的時候",
    example_jp: "お金が足りなくて、新しい車を買うどころではない。",
    example_zh: "錢不夠，根本沒辦法買新車。",
    prefix: ["動詞辭書形", "名詞"],
    memorized: false,
    page: 569,
  },
  {
    id: 328,
    grammar: "〜ものがある",
    meaning: "確實感到～",
    example_jp: "彼の成長には目を見張るものがある。",
    example_zh: "他的成長令人刮目相看。",
    prefix: ["動詞辭書形", "形容詞"],
    memorized: false,
    page: 576,
    supplement: "用來表達對事物的強烈評價",
  },
  {
    id: 329,
    grammar: "〜しだいだ",
    meaning: "取決於～",
    example_jp: "結果は、あなたの努力次第です。",
    example_zh: "結果的好壞取決於你的努力。",
    prefix: ["名詞"],
    memorized: false,
    page: 578,
  },
];
